use_frameworks!

platform :ios, '8.0'

target 'AJModuleService_Example' do
  pod 'AJModuleService', :path => '../'

  target 'AJModuleService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
